version: '3.8'

services:
  php-app:
    build: 
      context: ./php-app  # Builds the PHP app Docker image from the ./php-app directory
    ports:
      - "8080:80"  # Maps port 8080 on the host to port 80 in the container
    depends_on:
      - mysql  # Ensures MySQL starts before the PHP app
    volumes:
      - E:\dev\php\doc-test\php-app:/var/www/html
    networks:
      - app-network
    

  mysql:
    image: mysql:8.0  # Uses the official MySQL image
    ports:
      - "3306:3306"  # Maps port 3306 on the host to port 3306 in the container
    environment:
      MYSQL_ROOT_PASSWORD: root  # Root password for MySQL
      MYSQL_DATABASE: kikerdezo  # Initial database to create
      MYSQL_USER: svc-kikerdezo
      MYSQL_PASSWORD: 1DwQZx_ionUM([/*
    volumes:
      - ./sql/kikerdezo_last.sql:/docker-entrypoint-initdb.d/init.sql  # Persists MySQL data in a named volume
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8888:80"
    #restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network
volumes:
  mysql-data: # Declares a named volume for MySQL data persistence

networks:
  app-network:
    driver: bridge
